{% set version = "2.4.1" %}
{% set ver = version|replace(".", "_") %}

package:
  name: expat
  version: {{ version }}

source:
  url: https://github.com/libexpat/libexpat/releases/download/R_{{ ver }}/expat-{{ version }}.tar.bz2
  sha256: 2f9b6a580b94577b150a7d5617ad4643a4301a6616ff459307df3e225bcfbf40

build:
  number: 0
  run_exports:
    # changes soname at major versions, default settings OK
    # https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - libtool  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]

test:
  commands:
    - xmlwf -h

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Expat XML parser library in C

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
    - scopatz
